import { Template } from "@/types/editor";

export const TEMPLATES: Template[] = [
  // ─── YouTube ──────────────────────────────────────────────────
  {
    id: "yt-standard",
    name: "YouTube Padrão",
    category: "youtube",
    width: 1280,
    height: 720,
    backgroundColor: "#1a1a2e",
    previewGradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
    description: "Formato padrão 16:9 — mais usado no YouTube",
    tags: ["padrão", "16:9"],
  },
  {
    id: "yt-gaming",
    name: "Gaming / Esports",
    category: "youtube",
    width: 1280,
    height: 720,
    backgroundColor: "#0d0d0d",
    previewGradient: "linear-gradient(135deg, #0d0d0d 0%, #1a0033 50%, #ff006e 100%)",
    description: "Escuro e dinâmico para canais de games",
    tags: ["games", "dark"],
  },
  {
    id: "yt-vlog",
    name: "Vlog / Lifestyle",
    category: "youtube",
    width: 1280,
    height: 720,
    backgroundColor: "#fff9f0",
    previewGradient: "linear-gradient(135deg, #fff9f0 0%, #ffe0b2 100%)",
    description: "Quente e vibrante para vlogs e lifestyle",
    tags: ["vlog", "lifestyle"],
  },
  {
    id: "yt-tutorial",
    name: "Tutorial / Tech",
    category: "youtube",
    width: 1280,
    height: 720,
    backgroundColor: "#0a192f",
    previewGradient: "linear-gradient(135deg, #0a192f 0%, #112240 50%, #00b4d8 100%)",
    description: "Profissional para tutoriais e conteúdo tech",
    tags: ["tutorial", "tech"],
  },
  {
    id: "yt-reaction",
    name: "React / Podcast",
    category: "youtube",
    width: 1280,
    height: 720,
    backgroundColor: "#2d1b69",
    previewGradient: "linear-gradient(135deg, #2d1b69 0%, #11998e 100%)",
    description: "Colorido para reacts e podcasts",
    tags: ["react", "podcast"],
  },
  {
    id: "yt-minimalist",
    name: "Minimalista",
    category: "youtube",
    width: 1280,
    height: 720,
    backgroundColor: "#f5f5f5",
    previewGradient: "linear-gradient(135deg, #f5f5f5 0%, #e0e0e0 100%)",
    description: "Clean e elegante — perfeito para business",
    tags: ["minimalista", "clean"],
  },
  {
    id: "yt-neon",
    name: "Neon / Cyberpunk",
    category: "youtube",
    width: 1280,
    height: 720,
    backgroundColor: "#0a0a0a",
    previewGradient: "linear-gradient(135deg, #0a0a0a 0%, #ff00ff 50%, #00ffff 100%)",
    description: "Estilo cyberpunk com neon vibrante",
    tags: ["neon", "cyberpunk"],
  },
  {
    id: "yt-kids",
    name: "Infantil / Kids",
    category: "youtube",
    width: 1280,
    height: 720,
    backgroundColor: "#ffeb3b",
    previewGradient: "linear-gradient(135deg, #ffeb3b 0%, #ff5722 50%, #9c27b0 100%)",
    description: "Colorido e divertido para conteúdo infantil",
    tags: ["kids", "colorido"],
  },
  {
    id: "yt-cooking",
    name: "Culinária / Food",
    category: "youtube",
    width: 1280,
    height: 720,
    backgroundColor: "#8B4513",
    previewGradient: "linear-gradient(135deg, #ff6b35 0%, #f7931e 50%, #ffcd3c 100%)",
    description: "Apetitoso para canais de culinária",
    tags: ["food", "culinária"],
  },
  {
    id: "yt-fitness",
    name: "Fitness / Saúde",
    category: "youtube",
    width: 1280,
    height: 720,
    backgroundColor: "#1b2838",
    previewGradient: "linear-gradient(135deg, #1b2838 0%, #e63946 100%)",
    description: "Energético para conteúdo fitness e saúde",
    tags: ["fitness", "saúde"],
  },

  // ─── Instagram ────────────────────────────────────────────────
  {
    id: "ig-square",
    name: "Post Quadrado",
    category: "instagram",
    width: 1080,
    height: 1080,
    backgroundColor: "#ffffff",
    previewGradient: "linear-gradient(135deg, #833ab4, #fd1d1d, #fcb045)",
    description: "Formato quadrado clássico 1:1",
    tags: ["quadrado", "1:1"],
  },
  {
    id: "ig-portrait",
    name: "Post Retrato",
    category: "instagram",
    width: 1080,
    height: 1350,
    backgroundColor: "#f0f0f0",
    previewGradient: "linear-gradient(180deg, #667eea 0%, #764ba2 100%)",
    description: "Retrato 4:5 — maior alcance no feed",
    tags: ["retrato", "4:5"],
  },
  {
    id: "ig-landscape",
    name: "Post Paisagem",
    category: "instagram",
    width: 1080,
    height: 566,
    backgroundColor: "#1a1a2e",
    previewGradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)",
    description: "Formato paisagem 1.91:1",
    tags: ["paisagem"],
  },
  {
    id: "ig-carousel",
    name: "Carrossel",
    category: "instagram",
    width: 1080,
    height: 1080,
    backgroundColor: "#fafafa",
    previewGradient: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    description: "Slide para carrossel — formato quadrado",
    tags: ["carrossel"],
  },

  // ─── Stories / Reels ─────────────────────────────────────────
  {
    id: "stories-instagram",
    name: "Instagram Stories",
    category: "stories",
    width: 1080,
    height: 1920,
    backgroundColor: "#1a1a2e",
    previewGradient: "linear-gradient(180deg, #833ab4, #fd1d1d, #fcb045)",
    description: "Stories do Instagram 9:16",
    tags: ["stories", "9:16"],
  },
  {
    id: "stories-tiktok",
    name: "TikTok",
    category: "stories",
    width: 1080,
    height: 1920,
    backgroundColor: "#010101",
    previewGradient: "linear-gradient(180deg, #010101 0%, #69c9d0 50%, #ee1d52 100%)",
    description: "Formato TikTok / Reels vertical",
    tags: ["tiktok", "reels"],
  },
  {
    id: "stories-whatsapp",
    name: "WhatsApp Status",
    category: "stories",
    width: 1080,
    height: 1920,
    backgroundColor: "#075e54",
    previewGradient: "linear-gradient(180deg, #075e54 0%, #128c7e 100%)",
    description: "Status do WhatsApp 9:16",
    tags: ["whatsapp", "status"],
  },
  {
    id: "stories-youtube-shorts",
    name: "YouTube Shorts",
    category: "stories",
    width: 1080,
    height: 1920,
    backgroundColor: "#ff0000",
    previewGradient: "linear-gradient(180deg, #0f0f0f 0%, #cc0000 100%)",
    description: "YouTube Shorts vertical 9:16",
    tags: ["shorts", "youtube"],
  },

  // ─── Twitter / X ─────────────────────────────────────────────
  {
    id: "twitter-card",
    name: "Twitter/X Card",
    category: "twitter",
    width: 1200,
    height: 675,
    backgroundColor: "#15202b",
    previewGradient: "linear-gradient(135deg, #15202b 0%, #1da1f2 100%)",
    description: "Imagem para posts no Twitter/X",
    tags: ["twitter", "card"],
  },
  {
    id: "twitter-banner",
    name: "Twitter/X Header",
    category: "twitter",
    width: 1500,
    height: 500,
    backgroundColor: "#1da1f2",
    previewGradient: "linear-gradient(135deg, #1da1f2 0%, #0d8ecf 100%)",
    description: "Banner do perfil no Twitter/X",
    tags: ["banner", "header"],
  },

  // ─── LinkedIn ─────────────────────────────────────────────────
  {
    id: "li-post",
    name: "Post LinkedIn",
    category: "linkedin",
    width: 1200,
    height: 628,
    backgroundColor: "#0077b5",
    previewGradient: "linear-gradient(135deg, #0077b5 0%, #00a0dc 100%)",
    description: "Post padrão para LinkedIn",
    tags: ["linkedin", "post"],
  },
  {
    id: "li-banner",
    name: "Banner LinkedIn",
    category: "linkedin",
    width: 1584,
    height: 396,
    backgroundColor: "#004182",
    previewGradient: "linear-gradient(135deg, #004182 0%, #0077b5 100%)",
    description: "Banner do perfil do LinkedIn",
    tags: ["banner", "perfil"],
  },
  {
    id: "li-article",
    name: "Artigo LinkedIn",
    category: "linkedin",
    width: 744,
    height: 400,
    backgroundColor: "#ffffff",
    previewGradient: "linear-gradient(135deg, #ffffff 0%, #e8f4f8 100%)",
    description: "Imagem de capa para artigo no LinkedIn",
    tags: ["artigo"],
  },

  // ─── TikTok ───────────────────────────────────────────────────
  {
    id: "tiktok-cover",
    name: "TikTok Cover",
    category: "tiktok",
    width: 1080,
    height: 1920,
    backgroundColor: "#010101",
    previewGradient: "linear-gradient(180deg, #010101 0%, #69c9d0 100%)",
    description: "Capa de vídeo TikTok vertical",
    tags: ["cover", "vertical"],
  },
  {
    id: "tiktok-profile",
    name: "TikTok Perfil",
    category: "tiktok",
    width: 200,
    height: 200,
    backgroundColor: "#010101",
    previewGradient: "radial-gradient(circle, #69c9d0 0%, #ee1d52 100%)",
    description: "Foto de perfil TikTok",
    tags: ["perfil", "avatar"],
  },

  // ─── Facebook ─────────────────────────────────────────────────
  {
    id: "fb-post",
    name: "Post Facebook",
    category: "facebook",
    width: 1200,
    height: 630,
    backgroundColor: "#1877f2",
    previewGradient: "linear-gradient(135deg, #1877f2 0%, #42a5f5 100%)",
    description: "Imagem para post no Facebook",
    tags: ["post", "feed"],
  },
  {
    id: "fb-cover",
    name: "Capa Facebook",
    category: "facebook",
    width: 820,
    height: 312,
    backgroundColor: "#1877f2",
    previewGradient: "linear-gradient(135deg, #1877f2 0%, #0d47a1 100%)",
    description: "Foto de capa do perfil Facebook",
    tags: ["capa", "perfil"],
  },
  {
    id: "fb-story",
    name: "Facebook Story",
    category: "facebook",
    width: 1080,
    height: 1920,
    backgroundColor: "#1877f2",
    previewGradient: "linear-gradient(180deg, #1877f2 0%, #42a5f5 100%)",
    description: "Story do Facebook 9:16",
    tags: ["story"],
  },
  {
    id: "fb-event",
    name: "Evento Facebook",
    category: "facebook",
    width: 1920,
    height: 1080,
    backgroundColor: "#23272a",
    previewGradient: "linear-gradient(135deg, #23272a 0%, #1877f2 100%)",
    description: "Imagem de capa para eventos",
    tags: ["evento"],
  },

  // ─── Pinterest ────────────────────────────────────────────────
  {
    id: "pin-standard",
    name: "Pin Padrão",
    category: "pinterest",
    width: 1000,
    height: 1500,
    backgroundColor: "#e60023",
    previewGradient: "linear-gradient(180deg, #e60023 0%, #ad081b 100%)",
    description: "Pin padrão 2:3 — mais recomendado",
    tags: ["pin", "2:3"],
  },
  {
    id: "pin-square",
    name: "Pin Quadrado",
    category: "pinterest",
    width: 1000,
    height: 1000,
    backgroundColor: "#ad081b",
    previewGradient: "linear-gradient(135deg, #ad081b 0%, #e60023 100%)",
    description: "Pin quadrado 1:1",
    tags: ["quadrado"],
  },
  {
    id: "pin-infographic",
    name: "Infográfico",
    category: "pinterest",
    width: 800,
    height: 2000,
    backgroundColor: "#ffffff",
    previewGradient: "linear-gradient(180deg, #f8f8f8 0%, #e0e0e0 100%)",
    description: "Formato longo para infográficos",
    tags: ["infográfico", "longo"],
  },

  // ─── Presentation ─────────────────────────────────────────────
  {
    id: "pres-16-9",
    name: "Apresentação 16:9",
    category: "presentation",
    width: 1920,
    height: 1080,
    backgroundColor: "#ffffff",
    previewGradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    description: "Slide widescreen Full HD",
    tags: ["slides", "16:9"],
  },
  {
    id: "pres-4-3",
    name: "Apresentação 4:3",
    category: "presentation",
    width: 1024,
    height: 768,
    backgroundColor: "#ffffff",
    previewGradient: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    description: "Slide formato clássico 4:3",
    tags: ["slides", "4:3"],
  },
  {
    id: "pres-a4",
    name: "A4 / Documento",
    category: "presentation",
    width: 2480,
    height: 3508,
    backgroundColor: "#ffffff",
    previewGradient: "linear-gradient(180deg, #ffffff 0%, #f5f5f5 100%)",
    description: "Formato A4 para documentos e flyers",
    tags: ["a4", "documento", "flyer"],
  },

  // ─── Banner ───────────────────────────────────────────────────
  {
    id: "banner-leaderboard",
    name: "Leaderboard 728×90",
    category: "banner",
    width: 728,
    height: 90,
    backgroundColor: "#1a1a2e",
    previewGradient: "linear-gradient(90deg, #1a1a2e 0%, #0f3460 100%)",
    description: "Banner horizontal para topo de sites",
    tags: ["web", "horizontal"],
  },
  {
    id: "banner-rectangle",
    name: "Retângulo 300×250",
    category: "banner",
    width: 300,
    height: 250,
    backgroundColor: "#0f3460",
    previewGradient: "linear-gradient(135deg, #0f3460 0%, #533483 100%)",
    description: "Medium Rectangle — mais usado em ads",
    tags: ["web", "ads"],
  },
  {
    id: "banner-skyscraper",
    name: "Skyscraper 160×600",
    category: "banner",
    width: 160,
    height: 600,
    backgroundColor: "#533483",
    previewGradient: "linear-gradient(180deg, #533483 0%, #e94560 100%)",
    description: "Banner vertical para laterais",
    tags: ["web", "vertical"],
  },
  {
    id: "banner-email",
    name: "Email Header",
    category: "banner",
    width: 600,
    height: 200,
    backgroundColor: "#f8f9fa",
    previewGradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
    description: "Cabeçalho para email marketing",
    tags: ["email", "newsletter"],
  },

  // ─── Custom ───────────────────────────────────────────────────
  {
    id: "custom-hd",
    name: "Full HD 1920×1080",
    category: "custom",
    width: 1920,
    height: 1080,
    backgroundColor: "#1a1a2e",
    previewGradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)",
    description: "Full HD widescreen universal",
    tags: ["full hd", "1080p"],
  },
  {
    id: "custom-4k",
    name: "4K Ultra HD",
    category: "custom",
    width: 3840,
    height: 2160,
    backgroundColor: "#0a0a0a",
    previewGradient: "linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 100%)",
    description: "4K para máxima qualidade",
    tags: ["4k", "uhd"],
  },
  {
    id: "custom-square",
    name: "Quadrado 1000×1000",
    category: "custom",
    width: 1000,
    height: 1000,
    backgroundColor: "#ffffff",
    previewGradient: "linear-gradient(135deg, #e0e0e0 0%, #ffffff 100%)",
    description: "Quadrado versátil para múltiplas redes",
    tags: ["quadrado", "universal"],
  },
];

export const TEMPLATE_CATEGORIES = [
  { id: "youtube", label: "YouTube", icon: "📺" },
  { id: "instagram", label: "Instagram", icon: "📸" },
  { id: "stories", label: "Stories / Reels", icon: "📱" },
  { id: "tiktok", label: "TikTok", icon: "🎵" },
  { id: "facebook", label: "Facebook", icon: "👥" },
  { id: "twitter", label: "Twitter/X", icon: "🐦" },
  { id: "linkedin", label: "LinkedIn", icon: "💼" },
  { id: "pinterest", label: "Pinterest", icon: "📌" },
  { id: "presentation", label: "Apresentação", icon: "🖥️" },
  { id: "banner", label: "Banner / Ads", icon: "🎯" },
  { id: "custom", label: "Personalizado", icon: "✏️" },
] as const;

export function getTemplatesByCategory(category: string): Template[] {
  return TEMPLATES.filter((t) => t.category === category);
}

export function getTemplateById(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id);
}
